---
title: "Physicians"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r, echo = FALSE, eval = TRUE, results = "hide", warning = FALSE, message = FALSE}

#### Library ----
library(readxl)
library(dplyr)
library(tidyverse)

```

```{r, echo = FALSE, eval = TRUE, results = "hide", warning = FALSE, message = FALSE}

#### Theme ----
theme_elegante <- function(base_size = 10,
                           base_family = "Raleway"
)
{
  color.background = "#FFFFFF" # Chart Background
  color.grid.major = "#D9D9D9" # Chart Gridlines
  color.axis.text = "#666666" # 
  color.axis.title = "#666666" # 
  color.title = "#666666"
  color.subtitle = "#666666"
  strip.background.color = '#9999CC'
  
  ret <-
    theme_bw(base_size=base_size) +
    
    # Set the entire chart region to a light gray color
    theme(panel.background=element_rect(fill=color.background, color=color.background)) +
    theme(plot.background=element_rect(fill=color.background, color=color.background)) +
    theme(panel.border=element_rect(color=color.background)) +
    
    # Format the grid
    theme(panel.grid.major=element_line(color=color.grid.major,size=.55, linetype="dotted")) +
    theme(panel.grid.minor=element_line(color=color.grid.major,size=.55, linetype="dotted")) +
    theme(axis.ticks=element_blank()) +
    
    # Format the legend, but hide by default
    theme(legend.position="none") +
    theme(legend.background = element_rect(fill=color.background)) +
    theme(legend.text = element_text(size=base_size-3,color=color.axis.title, family = base_family)) +
    
    theme(strip.text.x = element_text(size=base_size,color=color.background, family = base_family)) +
    theme(strip.text.y = element_text(size=base_size,color=color.background, family = base_family)) +
    #theme(strip.background = element_rect(fill=strip.background.color, linetype="blank")) +
    theme(strip.background = element_rect(fill = "grey70", colour = NA)) +
    # theme(panel.border= element_rect(fill = NA, colour = "grey70", size = rel(1)))+
    # Set title and axis labels, and format these and tick marks
    theme(plot.title=element_text(color=color.title, 
                                  size=20, 
                                  vjust=1.25, 
                                  family=base_family, 
                                  hjust = 0.5
    )) +
    
    theme(plot.subtitle=element_text(color=color.subtitle, size=base_size+2, family = base_family,  hjust = 0.5))  +
    
    theme(axis.text.x=element_text(size=base_size,color=color.axis.text, family = base_family)) +
    theme(axis.text.y=element_text(size=base_size,color=color.axis.text, family = base_family)) +
    theme(text=element_text(size=base_size, color=color.axis.text, family = base_family)) +
    
    theme(axis.title.x=element_text(size=base_size+2,color=color.axis.title, vjust=0, family = base_family)) +
    theme(axis.title.y=element_text(size=base_size+2,color=color.axis.title, vjust=1.25, family = base_family)) +
    theme(plot.caption=element_text(size=base_size-2,color=color.axis.title, vjust=1.25, family = base_family)) +
    
    # Legend  
    theme(legend.text=element_text(size=base_size,color=color.axis.text, family = base_family)) +
    theme(legend.title=element_text(size=base_size,color=color.axis.text, family = base_family)) +
    theme(legend.key=element_rect(colour = color.background, fill = color.background)) +
    theme(legend.position="bottom", 
          legend.box = "horizontal", 
          legend.title = element_blank(),
          legend.key.width = unit(.75, "cm"),
          legend.key.height = unit(.75, "cm"),
          legend.spacing.x = unit(.25, 'cm'),
          legend.spacing.y = unit(.25, 'cm'),
          legend.margin = margin(t=0, r=0, b=0, l=0, unit="cm")) +
    
    # Plot margins
    theme(plot.margin = unit(c(.5, .5, .5, .5), "cm"))
  
  ret
}

```

```{r, echo = FALSE, eval = TRUE, results = "hide"}

#### General Data ----

Health <- read_excel("Health_2.xlsx")

```

```{r, echo = FALSE, eval = TRUE, warning = FALSE}

# Physicians (per 1,000 people) ----

# Long definition
# Physicians include generalist and specialist medical practitioners.
# Source
# World Health Organization's Global Health Workforce Statistics, OECD, supplemented by country data.

# Physicians Data
Health_Phys <- Health %>%
  select(Country, `Physiciansper1,000people2013-18`) %>%
  filter(`Physiciansper1,000people2013-18` != "..", Country %in%
           c("Argentina", "Chile", "Cuba", "Uruguay", "Italy", "Spain", "Finland",
             "Denmark", "Austrlia", "New Zealand", "Europe & Central Asia", "Belgium",
             "Croatia", "Norway", "Costa Rica", "United Kingdom", "North America",
             "Canada", "Japan", "Mexico", "Poland", "Latin America & Caribbean",
             "Brazil", "Colombia", "China", "Ecuador", "East Asia & Pacific",
             "Bolivia", "Panama", "World", "Paraguay", "Peru", "India", "Venezuela, RB",
             "United States", "Greece", "Austria", "Portugal", "Israel", "Germany",
             "Russian Federation", "Denmark", "Hungary")) %>%
  arrange(`Physiciansper1,000people2013-18`) # Reorder the data

Health_Phys$`Physiciansper1,000people2013-18` <- as.numeric(as.character(Health_Phys$`Physiciansper1,000people2013-18`)) #Transform column character to numeric

# Physicians Graphic

Health_Phys %>%
  mutate(Country = fct_reorder(Country, `Physiciansper1,000people2013-18`)) %>%
  ggplot(aes(x = Country, y = `Physiciansper1,000people2013-18`)) +
  geom_segment(aes(x = Country, xend = Country, y = 0, yend = `Physiciansper1,000people2013-18`), color = ifelse(Health_Phys$Country %in% c("Chile"), "dodgerblue3", "gray58"), size = ifelse(Health_Phys$Country %in% c("Chile"), 1.5, 0.8)) +
  geom_point(color = ifelse(Health_Phys$Country %in% c("Chile"), "dodgerblue3", "gray58"), size = ifelse(Health_Phys$Country %in% c("Chile"), 4.2, 2.5)) +
  coord_flip() +
  theme_elegante() +
  xlab("Country") +
  ylab("Physicians (per 1,000 people)") +
  labs(title = paste("What is the relationship between doctors and countries worldwide?"), 
       caption = "World Health Organization's Global Health Workforce Statistics, OECD, supplemented by country data.",
       subtitle = paste0("Situation of Chile and the world\n", "2013 - 2018" )) +
    geom_text(aes(label = Health_Phys$`Physiciansper1,000people2013-18`), hjust = -.8, nudge_x = 0, color = "gray46", size = 3.5) +
  scale_y_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)) +
  theme(panel.grid.major.y = element_blank(), panel.border = element_blank(), axis.ticks.y = element_blank()) +
  theme(axis.title.y=element_blank(),
        legend.position = "none")

```
